Xian Jia Le, Ben 56214537

# Question 1

**Q1.1**

**prompt 1**
> Your task is to generate a dataset for training a knowledge-grounded dialogue generation model <br><br> Generate 10 records related to physic

**answer 1**
<blockquote>
Creating a dataset for training a knowledge-grounded dialogue generation model typically involves providing a prompt or question and a corresponding answer or response. Here are 10 records related to physics:

1. **Prompt:** What is the fundamental force responsible for holding electrons in orbit around the nucleus of an atom?
   **Answer:** The fundamental force responsible for this is electromagnetic force.

2. **Prompt:** Explain the concept of Einstein's theory of relativity.
   **Answer:** Einstein's theory of relativity consists of two main theories: special relativity, which deals with objects moving at constant speeds, and general relativity, which describes the effect of gravity on space-time.

3. **Prompt:** What is the speed of light in a vacuum, and why is it considered a universal constant?
   **Answer:** The speed of light in a vacuum is approximately 299,792,458 meters per second (or about 186,282 miles per second). It is considered a universal constant because it remains the same for all observers, regardless of their relative motion.

4. **Prompt:** Describe the process of nuclear fusion and its significance.
   **Answer:** Nuclear fusion is the process by which two light atomic nuclei combine to form a heavier nucleus, releasing a tremendous amount of energy. It powers stars like our sun and is being researched for potential clean and sustainable energy sources on Earth.

5. **Prompt:** What is the Heisenberg Uncertainty Principle in quantum mechanics?
   **Answer:** The Heisenberg Uncertainty Principle states that it is impossible to simultaneously know the precise position and momentum of a particle. This fundamental principle highlights the inherent limitations of measurement in quantum mechanics.

6. **Prompt:** Explain the concept of black holes and their formation.
   **Answer:** Black holes are extremely dense regions in space where gravity is so strong that nothing, not even light, can escape their gravitational pull. They form when massive stars collapse under their own gravity.

7. **Prompt:** How does the concept of conservation of energy apply to physical systems?
   **Answer:** The conservation of energy states that in any isolated system, the total energy remains constant over time. Energy may change from one form to another (e.g., kinetic to potential), but the total energy remains unchanged.

8. **Prompt:** What are the four fundamental forces in the universe?
   **Answer:** The four fundamental forces are gravity, electromagnetism, the strong nuclear force, and the weak nuclear force. These forces govern the behavior of all matter and energy in the universe.

9. **Prompt:** Describe the concept of dark matter and its role in the universe.
   **Answer:** Dark matter is a mysterious and invisible substance that makes up a significant portion of the universe's mass. It doesn't emit, absorb, or interact with light, but its gravitational effects are essential for explaining the structure and motion of galaxies and galaxy clusters.

10. **Prompt:** What is the concept of wave-particle duality in quantum physics?
    **Answer:** Wave-particle duality is a fundamental principle in quantum physics that states that particles like electrons and photons exhibit both wave-like and particle-like properties, depending on how they are observed and measured. This duality challenges classical notions of particle behavior.
</blockquote>

**prompt 2**
> You are data engineer and now your task is to generate a dataset for training a knowledge-grounded dialogue generation model <br> <br> give 10 records related to medical health with the following columns: <br> Prompt, Answer

**answer 2**
<blockquote>
Certainly, here are 10 records related to medical health with the specified "Prompt" and "Answer" columns:

1. **Prompt:** What are the common symptoms of influenza (the flu)?
   **Answer:** Common symptoms of influenza include fever, cough, sore throat, body aches, fatigue, and sometimes, respiratory congestion.

2. **Prompt:** Explain the importance of vaccination in preventing infectious diseases.
   **Answer:** Vaccination is crucial because it helps build immunity against diseases without causing the illness itself, reducing the spread of infectious diseases and protecting individuals and communities.

3. **Prompt:** Describe the primary risk factors for cardiovascular disease.
   **Answer:** Primary risk factors for cardiovascular disease include high blood pressure, high cholesterol, smoking, obesity, and a sedentary lifestyle.

4. **Prompt:** What is the recommended daily intake of water for adults, and why is staying hydrated important?
   **Answer:** The recommended daily intake of water for adults is around 8-10 cups (64-80 ounces). Staying hydrated is essential as it supports bodily functions, regulates body temperature, and aids in digestion.

5. **Prompt:** What is Type 2 diabetes, and what lifestyle changes can help manage it?
   **Answer:** Type 2 diabetes is a chronic condition characterized by elevated blood sugar levels. Lifestyle changes such as maintaining a healthy diet, regular exercise, and weight management can help manage it.

6. **Prompt:** Explain the difference between a virus and a bacterium.
   **Answer:** Viruses are smaller than bacteria and require a host cell to reproduce. Bacteria are single-celled organisms capable of independent growth and reproduction.

7. **Prompt:** Discuss the benefits of regular physical activity on mental health.
   **Answer:** Regular physical activity can reduce stress, improve mood, boost self-esteem, and alleviate symptoms of anxiety and depression.

8. **Prompt:** What are the potential risks associated with prolonged sitting and a sedentary lifestyle?
   **Answer:** Prolonged sitting and a sedentary lifestyle can increase the risk of obesity, heart disease, diabetes, and musculoskeletal problems.

9. **Prompt:** Describe the importance of early cancer detection and screening.
   **Answer:** Early cancer detection through screening tests can lead to earlier treatment and better outcomes, as many cancers are more treatable in their early stages.

10. **Prompt:** Explain the concept of herd immunity in the context of vaccination.
    **Answer:** Herd immunity occurs when a significant portion of a population becomes immune to a disease, either through vaccination or previous infection. This reduces the spread of the disease and protects those who are vulnerable.
</blockquote>
    

## Q1.2

**prompt**

<blockquote>
{
  "date": "2018-02-20T19:15:08.841Z", 
  "history": [
    {
      "docIdx": 0, 
      "text": "hello", 
      "uid": "user1", 
      "utcTimestamp": "2018-02-20T19:15:16.038Z"
    }, 
    {
      "docIdx": 0, 
      "text": "hello there, I have not seen this movie so im going to take a minute to look it over :)", 
      "uid": "user2", 
      "utcTimestamp": "2018-02-20T19:15:36.022Z"
    }, 
    {
      "docIdx": 0, 
      "text": "Alright that is fine. What is the movie?", 
      "uid": "user1", 
      "utcTimestamp": "2018-02-20T19:15:49.258Z"
    }, 
    {
      "docIdx": 0, 
      "text": "The movie is The Social Network", 
      "uid": "user2", 
      "utcTimestamp": "2018-02-20T19:15:56.234Z"
    }, 
    {
      "docIdx": 0, 
      "text": "I have not seen that one either.", 
      "uid": "user1", 
      "utcTimestamp": "2018-02-20T19:16:26.551Z"
    }, 
    {
      "docIdx": 0, 
      "text": "It appears to be like a biographical movie about Mark Zuckerberg and when he creates Facebook.", 
      "uid": "user2", 
      "utcTimestamp": "2018-02-20T19:16:32.140Z"
    }, 
    {
      "docIdx": 0, 
      "text": "Ohh yes I remember hearing about that movie, but it was a long time ago it feels like.", 
      "uid": "user1", 
      "utcTimestamp": "2018-02-20T19:17:04.252Z"
    }, 
    {
      "docIdx": 0, 
      "text": "Rotten Tomatoes has rated it 96% so that's decent, and it is a movie from 2010", 
      "uid": "user2", 
      "utcTimestamp": "2018-02-20T19:17:08.213Z"
    }, 
    {
      "docIdx": 0, 
      "text": "may be worth watching!", 
      "uid": "user2", 
      "utcTimestamp": "2018-02-20T19:17:21.342Z"
    }, 
    {
      "docIdx": 1, 
      "text": "Yes I think it could be, although I personally do not like facebook as a company.", 
      "uid": "user1", 
      "utcTimestamp": "2018-02-20T19:18:05.350Z"
    }, 
    {
      "docIdx": 1, 
      "text": "the movie portrays the founding of social networking website Facebook and the resulting lawsuits. It even has Justin Timberlake in it, I don't think I've ever seen him act. ", 
      "uid": "user2", 
      "utcTimestamp": "2018-02-20T19:18:11.549Z"
    }, 
    {
      "docIdx": 1, 
      "text": "I have not seen him in any movies in years", 
      "uid": "user1", 
      "utcTimestamp": "2018-02-20T19:18:26.046Z"
    }, 
    {
      "docIdx": 1, 
      "text": "Any other big name actors in it?", 
      "uid": "user1", 
      "utcTimestamp": "2018-02-20T19:19:35.351Z"
    }, 
    {
      "docIdx": 1, 
      "text": "hmm so I just got a scene described to me, it turns out Mark was dumped so he made a blog about her ... kind of childish.... then he made a site for people to \"rate\" women on looks...the college put him on porbation. and then that captured the attention of two classmates , that how the trio came to work on facebook I guess.", 
      "uid": "user2", 
      "utcTimestamp": "2018-02-20T19:19:55.668Z"
    }, 
    {
      "docIdx": 1, 
      "text": "So it came out of Mark being kind of a douche, Makes sense when I think about the company ", 
      "uid": "user1", 
      "utcTimestamp": "2018-02-20T19:20:34.278Z"
    }, 
    {
      "docIdx": 2, 
      "text": "Jesse Eisenberg, Andrew Garfield, Armie Hammer , and Max Minghella, not famailiar with any of those, id have to look on IMBD", 
      "uid": "user2", 
      "utcTimestamp": "2018-02-20T19:20:42.059Z"
    }, 
    {
      "docIdx": 2, 
      "text": "I am not familiar\n with any of them either", 
      "uid": "user1", 
      "utcTimestamp": "2018-02-20T19:21:05.185Z"
    }, 
    {
      "docIdx": 2, 
      "text": "another scene came up, i guess this site was just for hrvard but then they expanded to Yale, Columbia, and Stanford... sounds very elite like lol", 
      "uid": "user2", 
      "utcTimestamp": "2018-02-20T19:21:34.893Z"
    }, 
    {
      "docIdx": 2, 
      "text": "Seems like it was intended for the elite, but he saw the amount of money to be made by globalizing it", 
      "uid": "user1", 
      "utcTimestamp": "2018-02-20T19:22:43.385Z"
    }, 
    {
      "docIdx": 2, 
      "text": "and go figure Sean Parker who co founded Napster is in on it with Mark to make Facebook, i guess he is the one who persuaded him to drop the THE  as it was called Thefacebook originally", 
      "uid": "user2", 
      "utcTimestamp": "2018-02-20T19:22:44.601Z"
    }, 
    {
      "docIdx": 2, 
      "text": "removing the word \"the\" was a smart choice atleast", 
      "uid": "user1", 
      "utcTimestamp": "2018-02-20T19:23:19.866Z"
    }, 
    {
      "docIdx": 3, 
      "text": "yeah, flows a bit better I suppose so you can say \"facebook me\" lol", 
      "uid": "user2", 
      "utcTimestamp": "2018-02-20T19:23:46.092Z"
    }, 
    {
      "docIdx": 3, 
      "text": "ah new scene, talking about all the lawsuits that came against him. ", 
      "uid": "user2", 
      "utcTimestamp": "2018-02-20T19:24:08.189Z"
    }, 
    {
      "docIdx": 3, 
      "text": "I feel like he has always been in trouble for the way he operates then", 
      "uid": "user1", 
      "utcTimestamp": "2018-02-20T19:24:24.002Z"
    }, 
    {
      "docIdx": 3, 
      "text": "Now it is the way he markets ads by listening through the phones", 
      "uid": "user1", 
      "utcTimestamp": "2018-02-20T19:24:38.500Z"
    }, 
    {
      "docIdx": 3, 
      "text": "ending sounds weird, they said it ends with him sending a friend request to his ex who dumped him.  ironic.", 
      "uid": "user2", 
      "utcTimestamp": "2018-02-20T19:24:54.913Z"
    }, 
    {
      "docIdx": 3, 
      "text": "Im sure that was just for the hollywood effect", 
      "uid": "user1", 
      "utcTimestamp": "2018-02-20T19:25:10.035Z"
    }, 
    {
      "docIdx": 3, 
      "text": "yeah, he is a very selfish type of person I think in reality", 
      "uid": "user2", 
      "utcTimestamp": "2018-02-20T19:25:15.982Z"
    }, 
    {
      "docIdx": 3, 
      "text": "I agree", 
      "uid": "user1", 
      "utcTimestamp": "2018-02-20T19:25:25.134Z"
    }
  ], 
  "rating": 2, 
  "status": 1, 
  "uid1LogInTime": "2018-02-20T19:15:08.841Z", 
  "uid1LogOutTime": "2018-02-20T19:25:26.348Z", 
  "uid1response": {
    "feedback": "I hate facebook and mark as a company", 
    "response": [
      2, 
      3, 
      5
    ], 
    "type": "finish"
  }, 
  "uid2LogInTime": "2018-02-20T19:15:08.854Z", 
  "uid2LogOutTime": "2018-02-20T19:25:42.640Z", 
  "uid2response": {
    "feedback": null, 
    "response": [
      1, 
      2, 
      3, 
      5
    ], 
    "type": "finish"
  }, 
  "user1_id": "USR1723", 
  "user2_id": "USR3213", 
  "whoSawDoc": [
    "user2"
  ], 
  "wikiDocumentIdx": 17
}

The above is a json from CMU DoG dataset. Your task is to transform it into the following columns: user_id, text, docIdx and ascending order with docIdx 
</blockquote>

**answer**
<blockquote>
Certainly, I can help you transform the provided JSON into the desired format with the columns: `user_id`, `text`, and `docIdx` in ascending order of `docIdx`. Here's the transformed data:

```
user_id   | text                                                                                     | docIdx
----------|------------------------------------------------------------------------------------------|-------
user1     | hello                                                                                    | 0
user2     | hello there, I have not seen this movie so I'm going to take a minute to look it over :) | 0
user1     | Alright that is fine. What is the movie?                                                  | 0
user2     | The movie is The Social Network                                                           | 0
user1     | I have not seen that one either.                                                           | 0
user2     | It appears to be like a biographical movie about Mark Zuckerberg and when he creates Facebook. | 0
user1     | Ohh yes I remember hearing about that movie, but it was a long time ago it feels like.    | 0
user2     | Rotten Tomatoes has rated it 96% so that's decent, and it is a movie from 2010             | 0
user2     | may be worth watching!                                                                    | 0
user1     | Yes I think it could be, although I personally do not like Facebook as a company.        | 1
user2     | the movie portrays the founding of the social networking website Facebook and the resulting lawsuits. It even has Justin Timberlake in it, I don't think I've ever seen him act. | 1
user1     | I have not seen him in any movies in years                                                | 1
user1     | Any other big name actors in it?                                                           | 1
user2     | hmm so I just got a scene described to me, it turns out Mark was dumped so he made a blog about her ... kind of childish.... then he made a site for people to "rate" women on looks...the college put him on probation. and then that captured the attention of two classmates, that's how the trio came to work on Facebook I guess. | 1
user1     | So it came out of Mark being kind of a douche, Makes sense when I think about the company   | 1
user2     | Jesse Eisenberg, Andrew Garfield, Armie Hammer, and Max Minghella, not familiar with any of those, I'd have to look on IMDb | 2
user1     | I am not familiar with any of them either                                                  | 2
user2     | another scene came up, I guess this site was just for Harvard, but then they expanded to Yale, Columbia, and Stanford... sounds very elite-like lol | 2
user1     | Seems like it was intended for the elite, but he saw the amount of money to be made by globalizing it | 2
user2     | and go figure Sean Parker who co-founded Napster is in on it with Mark to make Facebook, I guess he is the one who persuaded him to drop the "THE" as it was called Thefacebook originally | 2
user1     | removing the word "the" was a smart choice at least                                        | 2
user2     | yeah, flows a bit better I suppose so you can say "facebook me" lol                       | 3
user2     | ah new scene, talking about all the lawsuits that came against him.                         | 3
user1     | I feel like he has always been in trouble for the way he operates then                     | 3
user1     | Now it is the way he markets ads by listening through the phones                             | 3
user2     | ending sounds weird, they said it ends with him sending a friend request to his ex who dumped him. ironic. | 3
user1     | I'm sure that was just for the Hollywood effect                                              | 3
user2     | yeah, he is a very selfish type of person I think in reality                                | 3
user1     | I agree                                                                                       | 3
```

I've organized the data by user and sorted it in ascending order of `docIdx`. If you have any further requests or need additional assistance, please let me know!
</blockquote>

## Q1.3

**prompt**
<blockquote>
Now you are a senior programmer. Your task is to write a Python program to read json and to transform the above json into the following columns: user_id, docIdx, text and ascending order with docIdx. Remember to do error checking and prevent exceptional cases and consider the reusability
</blockquote>

**answer**
<blockquote>
Certainly! To create a reusable Python program that reads JSON data and transforms it into the desired format while handling errors gracefully, you can encapsulate the transformation logic into a function. Here's a program with a reusable function:

```python
import json

def transform_json_to_columns(json_data):
    try:
        # Parse the JSON data
        data = json.loads(json_data)

        # Initialize a list to store the transformed data
        transformed_data = []

        # Extract relevant information from the JSON
        history = data.get("history", [])
        for entry in history:
            docIdx = entry.get("docIdx")
            text = entry.get("text")
            user_id = entry.get("uid")

            # Check if docIdx, text, and user_id are present
            if docIdx is not None and text and user_id:
                transformed_data.append({
                    "user_id": user_id,
                    "docIdx": docIdx,
                    "text": text
                })

        # Sort the data by docIdx in ascending order
        transformed_data.sort(key=lambda x: x["docIdx"])

        return transformed_data

    except json.JSONDecodeError as e:
        print(f"Error parsing JSON: {e}")
        return []
    except Exception as e:
        print(f"An error occurred: {e}")
        return []

# Provided JSON data
json_data = '''
{
  "date": "2018-02-20T19:15:08.841Z", 
  "history": [
    {
      "docIdx": 0, 
      "text": "hello", 
      "uid": "user1", 
      "utcTimestamp": "2018-02-20T19:15:16.038Z"
    },
    # ... (the rest of the JSON data)
  ],
  "rating": 2, 
  "status": 1, 
  "uid1LogInTime": "2018-02-20T19:15:08.841Z", 
  "uid1LogOutTime": "2018-02-20T19:25:26.348Z", 
  "uid1response": {
    "feedback": "I hate facebook and mark as a company", 
    "response": [
      2, 
      3, 
      5
    ], 
    "type": "finish"
  },
  # ...
}
'''

# Transform the JSON data
transformed_data = transform_json_to_columns(json_data)

# Display the transformed data
for entry in transformed_data:
    print(f"user_id: {entry['user_id']}, docIdx: {entry['docIdx']}, text: {entry['text']}")
```

In this program, the `transform_json_to_columns` function takes the JSON data as input and returns the transformed data as a list of dictionaries. Error handling is implemented to catch JSON parsing errors and other exceptions.

You can reuse the `transform_json_to_columns` function with different JSON inputs by providing the JSON data as an argument to the function.
</blockquote>

In [10]:
import json

def transform_json_to_columns(json_data):
    try:
        # Parse the JSON data
        data = json.loads(json_data)

        # Initialize a list to store the transformed data
        transformed_data = []

        # Extract relevant information from the JSON
        history = data.get("history", [])
        for entry in history:
            docIdx = entry.get("docIdx")
            text = entry.get("text")
            user_id = entry.get("uid")

            # Check if docIdx, text, and user_id are present
            if docIdx is not None and text and user_id:
                transformed_data.append({
                    "user_id": user_id,
                    "docIdx": docIdx,
                    "text": text
                })

        # Sort the data by docIdx in ascending order
        transformed_data.sort(key=lambda x: x["docIdx"])

        return transformed_data

    except json.JSONDecodeError as e:
        print(f"Error parsing JSON: {e}")
        return []
    except Exception as e:
        print(f"An error occurred: {e}")
        return []

# Provided JSON data
json_data = r'''
{
  "date": "2018-02-20T19:15:08.841Z", 
  "history": [
    {
      "docIdx": 0, 
      "text": "hello", 
      "uid": "user1", 
      "utcTimestamp": "2018-02-20T19:15:16.038Z"
    }, 
    {
      "docIdx": 0, 
      "text": "hello there, I have not seen this movie so im going to take a minute to look it over :)", 
      "uid": "user2", 
      "utcTimestamp": "2018-02-20T19:15:36.022Z"
    }, 
    {
      "docIdx": 0, 
      "text": "Alright that is fine. What is the movie?", 
      "uid": "user1", 
      "utcTimestamp": "2018-02-20T19:15:49.258Z"
    }, 
    {
      "docIdx": 0, 
      "text": "The movie is The Social Network", 
      "uid": "user2", 
      "utcTimestamp": "2018-02-20T19:15:56.234Z"
    }, 
    {
      "docIdx": 0, 
      "text": "I have not seen that one either.", 
      "uid": "user1", 
      "utcTimestamp": "2018-02-20T19:16:26.551Z"
    }, 
    {
      "docIdx": 0, 
      "text": "It appears to be like a biographical movie about Mark Zuckerberg and when he creates Facebook.", 
      "uid": "user2", 
      "utcTimestamp": "2018-02-20T19:16:32.140Z"
    }, 
    {
      "docIdx": 0, 
      "text": "Ohh yes I remember hearing about that movie, but it was a long time ago it feels like.", 
      "uid": "user1", 
      "utcTimestamp": "2018-02-20T19:17:04.252Z"
    }, 
    {
      "docIdx": 0, 
      "text": "Rotten Tomatoes has rated it 96% so that's decent, and it is a movie from 2010", 
      "uid": "user2", 
      "utcTimestamp": "2018-02-20T19:17:08.213Z"
    }, 
    {
      "docIdx": 0, 
      "text": "may be worth watching!", 
      "uid": "user2", 
      "utcTimestamp": "2018-02-20T19:17:21.342Z"
    }, 
    {
      "docIdx": 1, 
      "text": "Yes I think it could be, although I personally do not like facebook as a company.", 
      "uid": "user1", 
      "utcTimestamp": "2018-02-20T19:18:05.350Z"
    }, 
    {
      "docIdx": 1, 
      "text": "the movie portrays the founding of social networking website Facebook and the resulting lawsuits. It even has Justin Timberlake in it, I don't think I've ever seen him act. ", 
      "uid": "user2", 
      "utcTimestamp": "2018-02-20T19:18:11.549Z"
    }, 
    {
      "docIdx": 1, 
      "text": "I have not seen him in any movies in years", 
      "uid": "user1", 
      "utcTimestamp": "2018-02-20T19:18:26.046Z"
    }, 
    {
      "docIdx": 1, 
      "text": "Any other big name actors in it?", 
      "uid": "user1", 
      "utcTimestamp": "2018-02-20T19:19:35.351Z"
    }, 
    {
      "docIdx": 1, 
      "text": "hmm so I just got a scene described to me, it turns out Mark was dumped so he made a blog about her ... kind of childish.... then he made a site for people to \"rate\" women on looks...the college put him on porbation. and then that captured the attention of two classmates , that how the trio came to work on facebook I guess.", 
      "uid": "user2", 
      "utcTimestamp": "2018-02-20T19:19:55.668Z"
    }, 
    {
      "docIdx": 1, 
      "text": "So it came out of Mark being kind of a douche, Makes sense when I think about the company ", 
      "uid": "user1", 
      "utcTimestamp": "2018-02-20T19:20:34.278Z"
    }, 
    {
      "docIdx": 2, 
      "text": "Jesse Eisenberg, Andrew Garfield, Armie Hammer , and Max Minghella, not famailiar with any of those, id have to look on IMBD", 
      "uid": "user2", 
      "utcTimestamp": "2018-02-20T19:20:42.059Z"
    }, 
    {
      "docIdx": 2, 
      "text": "I am not familiar\n with any of them either", 
      "uid": "user1", 
      "utcTimestamp": "2018-02-20T19:21:05.185Z"
    }, 
    {
      "docIdx": 2, 
      "text": "another scene came up, i guess this site was just for hrvard but then they expanded to Yale, Columbia, and Stanford... sounds very elite like lol", 
      "uid": "user2", 
      "utcTimestamp": "2018-02-20T19:21:34.893Z"
    }, 
    {
      "docIdx": 2, 
      "text": "Seems like it was intended for the elite, but he saw the amount of money to be made by globalizing it", 
      "uid": "user1", 
      "utcTimestamp": "2018-02-20T19:22:43.385Z"
    }, 
    {
      "docIdx": 2, 
      "text": "and go figure Sean Parker who co founded Napster is in on it with Mark to make Facebook, i guess he is the one who persuaded him to drop the THE  as it was called Thefacebook originally", 
      "uid": "user2", 
      "utcTimestamp": "2018-02-20T19:22:44.601Z"
    }, 
    {
      "docIdx": 2, 
      "text": "removing the word \"the\" was a smart choice atleast", 
      "uid": "user1", 
      "utcTimestamp": "2018-02-20T19:23:19.866Z"
    }, 
    {
      "docIdx": 3, 
      "text": "yeah, flows a bit better I suppose so you can say \"facebook me\" lol", 
      "uid": "user2", 
      "utcTimestamp": "2018-02-20T19:23:46.092Z"
    }, 
    {
      "docIdx": 3, 
      "text": "ah new scene, talking about all the lawsuits that came against him. ", 
      "uid": "user2", 
      "utcTimestamp": "2018-02-20T19:24:08.189Z"
    }, 
    {
      "docIdx": 3, 
      "text": "I feel like he has always been in trouble for the way he operates then", 
      "uid": "user1", 
      "utcTimestamp": "2018-02-20T19:24:24.002Z"
    }, 
    {
      "docIdx": 3, 
      "text": "Now it is the way he markets ads by listening through the phones", 
      "uid": "user1", 
      "utcTimestamp": "2018-02-20T19:24:38.500Z"
    }, 
    {
      "docIdx": 3, 
      "text": "ending sounds weird, they said it ends with him sending a friend request to his ex who dumped him.  ironic.", 
      "uid": "user2", 
      "utcTimestamp": "2018-02-20T19:24:54.913Z"
    }, 
    {
      "docIdx": 3, 
      "text": "Im sure that was just for the hollywood effect", 
      "uid": "user1", 
      "utcTimestamp": "2018-02-20T19:25:10.035Z"
    }, 
    {
      "docIdx": 3, 
      "text": "yeah, he is a very selfish type of person I think in reality", 
      "uid": "user2", 
      "utcTimestamp": "2018-02-20T19:25:15.982Z"
    }, 
    {
      "docIdx": 3, 
      "text": "I agree", 
      "uid": "user1", 
      "utcTimestamp": "2018-02-20T19:25:25.134Z"
    }
  ], 
  "rating": 2, 
  "status": 1, 
  "uid1LogInTime": "2018-02-20T19:15:08.841Z", 
  "uid1LogOutTime": "2018-02-20T19:25:26.348Z", 
  "uid1response": {
    "feedback": "I hate facebook and mark as a company", 
    "response": [
      2, 
      3, 
      5
    ], 
    "type": "finish"
  }, 
  "uid2LogInTime": "2018-02-20T19:15:08.854Z", 
  "uid2LogOutTime": "2018-02-20T19:25:42.640Z", 
  "uid2response": {
    "feedback": null, 
    "response": [
      1, 
      2, 
      3, 
      5
    ], 
    "type": "finish"
  }, 
  "user1_id": "USR1723", 
  "user2_id": "USR3213", 
  "whoSawDoc": [
    "user2"
  ], 
  "wikiDocumentIdx": 17
}
'''

# Transform the JSON data
transformed_data = transform_json_to_columns(json_data)

# Display the transformed data
for entry in transformed_data[0:5]:
    print(f"user_id: {entry['user_id']}, docIdx: {entry['docIdx']}, text: {entry['text']}")








user_id: user1, docIdx: 0, text: hello
user_id: user2, docIdx: 0, text: hello there, I have not seen this movie so im going to take a minute to look it over :)
user_id: user1, docIdx: 0, text: Alright that is fine. What is the movie?
user_id: user2, docIdx: 0, text: The movie is The Social Network
user_id: user1, docIdx: 0, text: I have not seen that one either.


# Question 2

**2.1**

p=3

**2.2**

![question 2.2](./Assets/Question%202.2.png)

**Q2.3**

![Question 2.3](./Assets/Question%202.3.png)

**Q2.4**

![Question 2.4](./Assets/Question%202.4.png)

# Question 3

**1.**

```SQL
select h.hacker_id,h.name
from Hackers h,
    (select hacker_id,count(submission_id) as num from Submissions Group by hacker_id) mycount
where
    h.hacker_id = mycount.hacker_id and
    mycount.num= (select max(countTable.num)
                    from (select count(submission_id) as num from Submissions Group by hacker_id) countTable)
order by h.hacker_id;

```

**2.**

```SQL
select t.task_id,t.task_description,mycount.num
from    Tasks t,
        (select task_id,count(submission_id) as num from Submissions Group by task_id) mycount
where   t.task_id = mycount.task_id and
        mycount.num=    (select max(countTable.num)
                        from (select count(submission_id) as num from Submissions Group by task_id) countTable)
order by t.task_id;
```

**3.**

```SQL
select s.submission_id, h.name, t.task_description
from Submissions s, Hackers h, Tasks t
where   s.hacker_id = h.hacker_id and
        s.task_id = t.task_id and
        s.score =(select max(score) from Submissions where submission_date = '2022-10-01') and
        s.submission_date = '2022-10-01'
order by s.submission_id;
```

**4.**

```SQL
select h.hacker_id, h.name
from    Hackers h,
        (
            select scoreTable.hacker_id, sum(scoreTable.maxScore) as totalScore
            from (select hacker_id, task_id, max(score) as maxScore
                from Submissions
                group by hacker_id, task_id) as scoreTable
            group by scoreTable.hacker_id
        ) as totalScoreTable
where (
        totalScoreTable.hacker_id = h.hacker_id and
        totalScoreTable.totalScore =(
                                        select max(sumScoreTable.totalScore)
                                        from (
                                            select sum(scoreTable.maxScore) as totalScore
                                                    from (select hacker_id, max(score) as maxScore
                                                            from Submissions
                                                            group by hacker_id, task_id
                                                            ) as scoreTable
                                            group by scoreTable.hacker_id
                                        ) as sumScoreTable
                                    )
        )
order by h.hacker_id DESC;
```

**5.**

```SQL
select h.hacker_id, h.name, t.bouns
from Hackers h, Tasks t,
    (
       select s1.submission_id, s2.hacker_id,s1.task_id, s2.fscore
        from (select * 
                from Submissions
                where task_id=25) as s1 right join
            (
                select hacker_id , max(score) as fscore
                from Submissions
                where task_id=25
                Group by hacker_id
            ) as s2
        on (s1.hacker_id=s2.hacker_id and 
            s1.score = s2.fscore)
        order by s2.fscore DESC, s1.submission_id
        limit 3
    ) as Top3Table
where (
        h.hacker_id=Top3Table.hacker_id and 
        t.task_id = Top3Table.task_id 
        )

```

**6.**

```SQL
select * 
from (
        select t1.hacker_id, h.name,h.Bank_acount,sum(t2.bouns) as total_bonus
        from Hackers h, 
            (select * from (
                    select s1.task_id,s1.hacker_id, s1.fscore,row_number() over (partition by s1.task_id order by s1.fscore DESC) as ranking 
                    from (select task_id, hacker_id , max(score) as fscore 
                          from Submissions
                           Group by task_id, hacker_id
                        ) as s1
                ) as rankTable
                where ranking<=3
            ) as t1
            left join Tasks as t2
            on t1.task_id = t2.task_id
        where h.hacker_id = t1.hacker_id
        group by t1.hacker_id
        order by total_bonus DESC, h.hacker_id    
    ) as ftable
where ftable.total_bonus <> 0
```

# Question 4

**1**

Content based approach used the given metadata from user and given meta from the content to construct a model for predicting the likeness of the content for the user and recommend similar content based on it. 


Collaborative filtering approach uses past interaction records between user and item, such as purchasing history, rating history etc, to generate model for predicting the likeness of the content and recommend similar content based on it. If someone who watch a certain movie, the one who is similar to him will be recommended to that movie


**2**

Cold start problem refers to that the system can not form the proper relationship between item and the user which result in giving wrong recommendation. There are two types of cold start problem: product cold-start and user cold-start. Product cold-start means there is no enough information about the new product and user cold-start means there is almost no data available on the user.

To minimize the cold-start problem. There are the following method:

1.  By analyzing the cookies of the new users to identify what website or ads they have watched before in order to form the features vector for them.
2.  Assign the average feature vector from all user to the new user.
3.  Recommend the popular item to the user.

In [39]:
#3
import numpy as np

NUM_USERS=943
NUM_MOVIES=1682

def ReadFile(path:str,delimiter='\t'):
    try:
        data = np.loadtxt(path, delimiter=delimiter, unpack=True,encoding="utf-8")
        return data.T
    except Exception as e:
        print(f"An error occurred: {e}")
        return None
    

# convert data into movie X user matrix 
def Convert_To_MovieUser(data, num_user, num_items):
    records=data.tolist()
    # dict
    item_data = {}

    for record in records: # loop record
        user, item, rate, timestamp = record
        if item not in item_data:
            item_data[item] = {}
        item_data[item][user] = rate

    # Create a list of items and a list of users
    items = sorted(item_data.keys()) # item id 1,2,3,
    users = sorted(set(user for data in item_data.values() for user in data.keys()))
    print(items[:5])
    print(users[:5])
    # create empty array
    result =np.zeros(shape=(num_items,num_user)) 
    for i, item in enumerate(items):
        for j, user in enumerate(users):
            if user in item_data[item]: 
                result[int(item)-1][int(user)-1] = item_data[item][user]

    return result



    
train_dataset=ReadFile("./ml-100k/ua.base") # some movie is not rate
print(f"train shape = {train_dataset.shape}")
print(f"user id {train_dataset[0][0]} item {train_dataset[0][1]} rate :{train_dataset[0][2]} timestamp :{train_dataset[0][0]}")


result = Convert_To_MovieUser(train_dataset,NUM_USERS,NUM_MOVIES)
print(f"shape= {result.shape} first 3 {result[:3]}")
train_dataset=result
print(f"move 1 --- user-1: {train_dataset[0][0]} user-2: {train_dataset[0][1]}    ...... ")


train shape = (90570, 4)
user id 1.0 item 1.0 rate :5.0 timestamp :1.0
[1.0, 2.0, 3.0, 4.0, 5.0]
[1.0, 2.0, 3.0, 4.0, 5.0]
shape= (1682, 943) first 3 [[5. 4. 0. ... 5. 0. 0.]
 [3. 0. 0. ... 0. 0. 5.]
 [4. 0. 0. ... 0. 0. 0.]]
move 1 --- user-1: 5.0 user-2: 4.0    ...... 


In [22]:
def normalize_matrix_with_mask(result, mask):
    column_means = np.mean(result, axis=0)
    normalized_result = np.where(mask, result - column_means, 0.0)
    return normalized_result,column_means

masked       = (train_dataset != 0).astype(int)
Ynorm, Ymean = normalize_matrix_with_mask(train_dataset, masked)

In [23]:
import tensorflow as tf
from tensorflow import keras

def cost_func(X, W, b, Y, R, lambda_):
    j = (tf.linalg.matmul(X, tf.transpose(W)) + b - Y)*R
    J = 0.5 * tf.reduce_sum(j**2) + (lambda_/2) * (tf.reduce_sum(X**2) + tf.reduce_sum(W**2))
    return J



num_movies, num_users = train_dataset.shape
num_features = 100

# Set Initial Parameters (W, X), use tf.Variable to track these variables
tf.random.set_seed(1234) # for consistent results
W = tf.Variable(tf.random.normal((num_users,  num_features),dtype=tf.float64),  name='W')
X = tf.Variable(tf.random.normal((num_movies, num_features),dtype=tf.float64),  name='X')
b = tf.Variable(tf.random.normal((1,          num_users),   dtype=tf.float64),  name='b')

optimizer = keras.optimizers.Adam(learning_rate=1e-1)

iterations = 1000
lambda_ = 1
for iter in range(iterations):
    with tf.GradientTape() as tape:
        
        cost_value = cost_func(X, W, b, Ynorm, masked, lambda_)

    grads = tape.gradient( cost_value, [X,W,b] )

    optimizer.apply_gradients( zip(grads, [X,W,b]) )

    # Log periodically.
    if iter % 20 == 0:
        print(f"Training loss at iteration {iter}: {cost_value:0.1f}")

Training loss at iteration 0: 5195875.7
Training loss at iteration 20: 156253.2
Training loss at iteration 40: 63458.3
Training loss at iteration 60: 38068.9
Training loss at iteration 80: 26439.2
Training loss at iteration 100: 19927.0
Training loss at iteration 120: 15888.8
Training loss at iteration 140: 13242.2
Training loss at iteration 160: 11439.3
Training loss at iteration 180: 10170.7
Training loss at iteration 200: 9251.7
Training loss at iteration 220: 8568.0
Training loss at iteration 240: 8046.5
Training loss at iteration 260: 7639.2
Training loss at iteration 280: 7314.0
Training loss at iteration 300: 7048.9
Training loss at iteration 320: 6828.6
Training loss at iteration 340: 6642.3
Training loss at iteration 360: 6482.4
Training loss at iteration 380: 6343.4
Training loss at iteration 400: 6221.0
Training loss at iteration 420: 6112.4
Training loss at iteration 440: 6015.2
Training loss at iteration 460: 5927.5
Training loss at iteration 480: 5848.1
Training loss at i

In [24]:
prediction = np.matmul(X.numpy(), np.transpose(W.numpy())) + b.numpy()

print(f"prediction:")
print(prediction[0:3])
print(f"train data set")
print(train_dataset[0:3])

prediction:
[[4.47121744 3.90791312 2.58141951 ... 4.90594815 3.28004964 3.23715004]
 [2.46130921 2.39352505 2.84212171 ... 3.74988025 4.69602359 4.60846987]
 [3.40665383 3.04753257 2.82411685 ... 3.83060395 4.05399343 2.82923497]]
train data set
[[5. 4. 0. ... 5. 0. 0.]
 [3. 0. 0. ... 0. 0. 5.]
 [4. 0. 0. ... 0. 0. 0.]]


In [36]:
test_dataset=ReadFile("./ml-100k/ua.test")
movie_user_test = Convert_To_MovieUser(test_dataset,NUM_USERS,NUM_MOVIES)
print(movie_user_test[0:3])
print(movie_user_test.shape)

mask_test       = (movie_user_test != 0).astype(int)
print(prediction[mask_test==1])
print(movie_user_test[mask_test==1])


loss_with_prediction = np.sum(np.abs(prediction[mask_test==1]-movie_user_test[mask_test==1]))
print(f"loss_with_prediction :{loss_with_prediction}")

loss_with_original = np.sum(np.abs(train_dataset[mask_test==1]-movie_user_test[mask_test==1]))
print(f"loss_with_original :{loss_with_original}")

print(f"Improvement : {loss_with_original-loss_with_prediction}")

[1.0, 2.0, 3.0, 4.0, 5.0]
[1.0, 2.0, 3.0, 4.0, 5.0]
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
(1682, 943)
[3.0413075  3.16251533 3.22947077 ... 2.62759055 2.16505899 2.94692104]
[4. 4. 3. ... 2. 1. 1.]
loss_with_prediction :8184.89339740904
loss_with_original :33833.0
Improvement : 25648.10660259096
