In [1]:
from sklearn import tree,datasets,preprocessing
from sklearn.metrics import accuracy_score, confusion_matrix
import numpy as np

In [2]:
iris=datasets.load_iris()

In [3]:
print(iris.data[0]," ", iris.target[0])
print(iris.target_names)

[5.1 3.5 1.4 0.2]   0
['setosa' 'versicolor' 'virginica']


In [4]:
le = preprocessing.LabelEncoder()
label=le.fit_transform(iris.target_names)
print(label)

[0 1 2]


In [5]:
clf=tree.DecisionTreeClassifier(max_depth=3,criterion="entropy")
clf=clf.fit(iris.data,iris.target)

In [6]:
import graphviz
dot_data = tree.export_graphviz(clf,out_file=None,feature_names=iris.feature_names,class_names=iris.target_names, filled=True)
graph=graphviz.Source(dot_data)
graph.render("Iris",view=True)

'Iris.pdf'

Prediction

In [13]:
# XTest = np.array([
#     [4.6,3.5,1.1,0.25],
#     [5.7,2.5,2.8,1.2],
#     [7.3,2.8,6.6,2.2],
# ])
XTest=iris.data
Target=iris.target
Prediction = clf.predict(XTest)
print(iris.target_names[Prediction[0]])

setosa


In [14]:

print("Accurary Score",accuracy_score(Target,Prediction))
print("confusion matrix")
print(confusion_matrix(Target,Prediction))

Accurary Score 0.9733333333333334
confusion matrix
[[50  0  0]
 [ 0 47  3]
 [ 0  1 49]]


In [15]:
print(clf.tree_.value)

[[[50. 50. 50.]]

 [[50.  0.  0.]]

 [[ 0. 50. 50.]]

 [[ 0. 49.  5.]]

 [[ 0. 47.  1.]]

 [[ 0.  2.  4.]]

 [[ 0.  1. 45.]]

 [[ 0.  1.  2.]]

 [[ 0.  0. 43.]]]


In [16]:
print(clf.decision_path(XTest).todense())

[[1 1 0 ... 0 0 0]
 [1 1 0 ... 0 0 0]
 [1 1 0 ... 0 0 0]
 ...
 [1 0 1 ... 1 0 1]
 [1 0 1 ... 1 0 1]
 [1 0 1 ... 1 0 1]]
