Load libraries

In [1]:
import pandas as pd
from sklearn import tree,datasets,preprocessing
from sklearn.metrics import accuracy_score, confusion_matrix
from sklearn.model_selection import train_test_split
from scipy.io import arff
import graphviz
import numpy as np


load dataset

In [2]:
RawData=arff.loadarff("./Dataset/vertebral_column_data/column_3C_weka.arff")
#RawData = np.loadtxt("./Dataset/vertebral_column_data/column_3C.dat", delimiter=' ')
print(RawData[0])

[( 63.0278175 , 22.55258597,  39.60911701,  40.47523153,  98.67291675, -2.54399986e-01, b'Hernia')
 ( 39.05695098, 10.06099147,  25.01537822,  28.99595951, 114.4054254 ,  4.56425864e+00, b'Hernia')
 ( 68.83202098, 22.21848205,  50.09219357,  46.61353893, 105.9851355 , -3.53031731e+00, b'Hernia')
 ( 69.29700807, 24.65287791,  44.31123813,  44.64413017, 101.8684951 ,  1.12115234e+01, b'Hernia')
 ( 49.71285934,  9.65207488,  28.317406  ,  40.06078446, 108.1687249 ,  7.91850062e+00, b'Hernia')
 ( 40.25019968, 13.92190658,  25.1249496 ,  26.32829311, 130.3278713 ,  2.23065173e+00, b'Hernia')
 ( 53.43292815, 15.86433612,  37.16593387,  37.56859203, 120.5675233 ,  5.98855070e+00, b'Hernia')
 ( 45.36675362, 10.75561143,  29.03834896,  34.61114218, 117.2700675 , -1.06758708e+01, b'Hernia')
 ( 43.79019026, 13.5337531 ,  42.69081398,  30.25643716, 125.0028927 ,  1.32890182e+01, b'Hernia')
 ( 36.68635286,  5.01088412,  41.9487509 ,  31.67546874,  84.24141517,  6.64437117e-01, b'Hernia')
 ( 49.7066

In [3]:
Data = pd.DataFrame(RawData[0])
FeatureName=Data.columns
Data.iloc[:,6]=Data.iloc[:,6].str.decode('utf-8')
print(Data.iloc[0:2,:])
print("------------------------------------------")
print(FeatureName)

   pelvic_incidence  pelvic_tilt  lumbar_lordosis_angle  sacral_slope  \
0         63.027817    22.552586              39.609117     40.475232   
1         39.056951    10.060991              25.015378     28.995960   

   pelvic_radius  degree_spondylolisthesis   class  
0      98.672917                 -0.254400  Hernia  
1     114.405425                  4.564259  Hernia  
------------------------------------------
Index(['pelvic_incidence', 'pelvic_tilt', 'lumbar_lordosis_angle',
       'sacral_slope', 'pelvic_radius', 'degree_spondylolisthesis', 'class'],
      dtype='object')


Assign the data and target

In [4]:
XData=np.array(Data.iloc[:,0:5])
YLabels=np.array(Data.iloc[:,6])
LabelEncoder= preprocessing.LabelEncoder()
YTarget=LabelEncoder.fit_transform(YLabels)
ClassNames=LabelEncoder.classes_
print(XData[0],YTarget[0])
print("ClassName: ", ClassNames)

[63.0278175  22.55258597 39.60911701 40.47523153 98.67291675] 0
ClassName:  ['Hernia' 'Normal' 'Spondylolisthesis']


Spilt the data 7:3

In [5]:
XTrain73, XTest73,YTrain73, YTest73 = train_test_split(XData,YTarget,test_size=0.3,random_state=1,stratify=YTarget)
print(len(YTrain73)/len(XData))
print(YTrain73)

0.7
[1 2 1 0 2 1 1 2 1 2 0 1 2 2 2 2 2 2 1 1 2 2 2 0 1 2 2 1 1 1 2 1 1 2 2 1 2
 0 0 2 2 2 2 2 1 0 2 0 2 2 2 1 1 2 2 0 1 1 1 2 1 2 2 2 0 2 2 1 2 0 1 2 2 0
 2 0 2 0 2 2 2 1 1 1 2 1 2 2 0 1 2 0 0 0 0 2 1 1 2 2 1 0 0 2 2 0 2 2 0 2 0
 1 0 2 1 2 2 1 2 2 2 2 2 2 2 1 0 0 2 1 1 0 2 1 1 1 0 0 0 2 1 0 2 2 2 1 2 1
 2 1 0 2 2 2 2 0 1 2 1 1 2 1 0 1 0 2 2 2 2 2 0 1 2 1 2 1 1 2 2 1 1 2 2 0 2
 0 1 2 1 0 2 1 2 2 1 2 1 1 0 1 2 1 2 1 0 1 0 1 1 1 2 2 2 2 2 1 2]


construct decision tree

In [6]:
DecisionTree73=tree.DecisionTreeClassifier(criterion="entropy",max_depth=4,random_state=1)
DecisionTree73=DecisionTree73.fit(XTrain73,YTrain73)
# YPredict73 = DecisionTree73.predict(XTest73)
# print("Tree(7 train , 3 test): ",accuracy_score(YTest73,YPredict73))

Visualiztion Decision Tree

In [7]:
dot_data73 = tree.export_graphviz(DecisionTree73,out_file=None,feature_names=FeatureName[0:5],class_names=ClassNames, filled=True)
graph=graphviz.Source(dot_data73)
graph.render("Vertebral Column73",view=True)

'Vertebral Column73.pdf'

construct tree in 9:1

In [8]:
XTrain91, XTest91,YTrain91, YTest91 = train_test_split(XData,YTarget,test_size=0.1,random_state=1,stratify=YTarget)
print(len(YTrain91)/len(XData))
DecisionTree91=tree.DecisionTreeClassifier(criterion="entropy",max_depth=4,random_state=1)
DecisionTree91=DecisionTree91.fit(XTrain91,YTrain91)
dot_data91 = tree.export_graphviz(DecisionTree91,out_file=None,feature_names=FeatureName[0:5],class_names=ClassNames, filled=True)
graph=graphviz.Source(dot_data91)
graph.render("Vertebral Column91",view=True)

0.9


'Vertebral Column91.pdf'

construct Decision Tree into 5:5

In [9]:
XTrain55, XTest55,YTrain55, YTest55 = train_test_split(XData,YTarget,test_size=0.5,random_state=1,stratify=YTarget)
print(len(YTrain55)/len(XData))
DecisionTree55=tree.DecisionTreeClassifier(criterion="entropy",max_depth=4,random_state=1)
DecisionTree55=DecisionTree55.fit(XTrain55,YTrain55)
dot_data55 = tree.export_graphviz(DecisionTree55,out_file=None,feature_names=FeatureName[0:5],class_names=ClassNames, filled=True)
graph=graphviz.Source(dot_data55)
graph.render("Vertebral Column55",view=True)

0.5


'Vertebral Column55.pdf'

construct Decision Tree into 3:7

In [10]:
XTrain37, XTest37,YTrain37, YTest37 = train_test_split(XData,YTarget,test_size=0.7,random_state=1,stratify=YTarget)
print(len(YTrain37)/len(XData))
DecisionTree37=tree.DecisionTreeClassifier(criterion="entropy",max_depth=4,random_state=1)
DecisionTree37=DecisionTree37.fit(XTrain37,YTrain37)
dot_data37 = tree.export_graphviz(DecisionTree37,out_file=None,feature_names=FeatureName[0:5],class_names=ClassNames, filled=True)
graph=graphviz.Source(dot_data37)
graph.render("Vertebral Column37",view=True)

0.3


'Vertebral Column37.pdf'

Contruct tree in 1:9

In [11]:
XTrain19, XTest19,YTrain19, YTest19 = train_test_split(XData,YTarget,test_size=0.9,random_state=1,stratify=YTarget)
print(len(YTrain19)/len(XData))
DecisionTree19=tree.DecisionTreeClassifier(criterion="entropy",max_depth=4,random_state=1)
DecisionTree19=DecisionTree19.fit(XTrain19,YTrain19)
dot_data19 = tree.export_graphviz(DecisionTree19,out_file=None,feature_names=FeatureName[0:5],class_names=ClassNames, filled=True)
graph=graphviz.Source(dot_data19)
graph.render("Vertebral Column19",view=True)

0.1


'Vertebral Column19.pdf'

Score

In [12]:
YPredict91 = DecisionTree91.predict(XTest91)
YPredict73 = DecisionTree73.predict(XTest73)
YPredict55 = DecisionTree55.predict(XTest55)
YPredict37 = DecisionTree37.predict(XTest37)
YPredict19 = DecisionTree19.predict(XTest19)
print("Accurary Score")
print("Tree(9 train , 1 test): ",accuracy_score(YTest91,YPredict91))
print("Tree(7 train , 3 test): ",accuracy_score(YTest73,YPredict73))
print("Tree(5 train , 5 test): ",accuracy_score(YTest55,YPredict55))
print("Tree(3 train , 7 test): ",accuracy_score(YTest37,YPredict37))
print("Tree(1 train , 9 test): ",accuracy_score(YTest19,YPredict19))

print("confusion matrix")
print("Tree(9 train , 1 test): ")
print(confusion_matrix(YTest91,YPredict91))
print("---------------------------------------------")
print("Tree(7 train , 3 test): ")
print(confusion_matrix(YTest73,YPredict73))
print("---------------------------------------------")
print("Tree(5 train , 5 test): ")
print(confusion_matrix(YTest55,YPredict55))
print("---------------------------------------------")
print("Tree(3 train , 7 test): ")
print(confusion_matrix(YTest37,YPredict37))
print("---------------------------------------------")
print("Tree(1 train , 9 test): ")
print(confusion_matrix(YTest19,YPredict19))

Accurary Score
Tree(9 train , 1 test):  0.7419354838709677
Tree(7 train , 3 test):  0.7096774193548387
Tree(5 train , 5 test):  0.6387096774193548
Tree(3 train , 7 test):  0.6589861751152074
Tree(1 train , 9 test):  0.5770609318996416
confusion matrix
Tree(9 train , 1 test): 
[[ 4  1  1]
 [ 3  6  1]
 [ 0  2 13]]
---------------------------------------------
Tree(7 train , 3 test): 
[[11  7  0]
 [ 8 20  2]
 [ 4  6 35]]
---------------------------------------------
Tree(5 train , 5 test): 
[[13 16  1]
 [10 34  6]
 [ 2 21 52]]
---------------------------------------------
Tree(3 train , 7 test): 
[[20 18  4]
 [ 8 41 21]
 [11 12 82]]
---------------------------------------------
Tree(1 train , 9 test): 
[[29 17  8]
 [17 42 31]
 [12 33 90]]


In [32]:
SeqDecision= DecisionTree73.decision_path(XTest73).todense()
for i in range(len(SeqDecision)):
    if(YPredict73[i]!=YTest73[i]):
            if(ClassNames[YPredict73[i]]=="Hernia"):
                if(ClassNames[YTest73[i]]!="Spondylolisthesis"):
                    print("Predict: ",ClassNames[YPredict73[i]], "acutal: ",ClassNames[YTest73[i]],"            ",SeqDecision[i])
print("")
for i in range(len(SeqDecision)):
    if(YPredict73[i]!=YTest73[i]):
            if(ClassNames[YPredict73[i]]=="Normal"):
                if(ClassNames[YTest73[i]]!="Spondylolisthesis"):
                    print("Predict: ",ClassNames[YPredict73[i]], "acutal: ",ClassNames[YTest73[i]],"            ",SeqDecision[i])

Predict:  Hernia acutal:  Normal              [[1 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]]
Predict:  Hernia acutal:  Normal              [[1 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]]
Predict:  Hernia acutal:  Normal              [[1 1 0 0 0 0 0 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]]
Predict:  Hernia acutal:  Normal              [[1 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]]
Predict:  Hernia acutal:  Normal              [[1 1 1 0 1 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]]
Predict:  Hernia acutal:  Normal              [[1 1 1 0 1 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]]
Predict:  Hernia acutal:  Normal              [[1 1 1 0 1 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]]
Predict:  Hernia acutal:  Normal              [[1 0 0 0 0 0 0 0 0 0 0 0 1 1 1 0 1 0 0 0 0 0 0 0 0]]
Predict:  Normal acutal:  Hernia              [[1 1 0 0 0 0 0 1 1 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0]]
Predict:  Normal acutal:  Hernia              [[1 1 0 0 0 0 0 1 1 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0]]
